--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ExodusDevs/Geometry
build-by-default: true
branches:
- master
projects:
  Geometry:
    path: ""
    model: virion
    type: library
...
